spring:
  application:
    name: "JavaTech"

  # Налаштування MongoDB
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/
      database: JavaTech

    # Налаштування Redis
    redis:
      host: localhost
      port: 6379
      password: redis123
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

jwt:
  expirationMs: 86400000